server:
  Port: :5000
  ReadTimeout: 5
  WriteTimeout: 5
  CtxDefaultTimeout: 12
  MaxConnectionIdle: 5
  Timeout: 15
  MaxConnectionAge: 5
  Time: 120

postgres:
  PostgresqlHost: "database"
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: postgres
  PostgresqlSslmode: false
  PgDriver: pgx

shortener:
  StringLength: 10
  Runes: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_"