// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: internal/url_shortener/proto/url_shortener.proto

package shortenerService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LongUrl string `protobuf:"bytes,1,opt,name=longUrl,proto3" json:"longUrl,omitempty"`
}

func (x *UCRequest) Reset() {
	*x = UCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_url_shortener_proto_url_shortener_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UCRequest) ProtoMessage() {}

func (x *UCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_url_shortener_proto_url_shortener_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UCRequest.ProtoReflect.Descriptor instead.
func (*UCRequest) Descriptor() ([]byte, []int) {
	return file_internal_url_shortener_proto_url_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *UCRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

type UCResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=shortUrl,proto3" json:"shortUrl,omitempty"`
}

func (x *UCResponse) Reset() {
	*x = UCResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_url_shortener_proto_url_shortener_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UCResponse) ProtoMessage() {}

func (x *UCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_url_shortener_proto_url_shortener_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UCResponse.ProtoReflect.Descriptor instead.
func (*UCResponse) Descriptor() ([]byte, []int) {
	return file_internal_url_shortener_proto_url_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *UCResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type UGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=shortUrl,proto3" json:"shortUrl,omitempty"`
}

func (x *UGRequest) Reset() {
	*x = UGRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_url_shortener_proto_url_shortener_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UGRequest) ProtoMessage() {}

func (x *UGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_url_shortener_proto_url_shortener_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UGRequest.ProtoReflect.Descriptor instead.
func (*UGRequest) Descriptor() ([]byte, []int) {
	return file_internal_url_shortener_proto_url_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *UGRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type UGResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LongUrl string `protobuf:"bytes,1,opt,name=longUrl,proto3" json:"longUrl,omitempty"`
}

func (x *UGResponse) Reset() {
	*x = UGResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_url_shortener_proto_url_shortener_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UGResponse) ProtoMessage() {}

func (x *UGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_url_shortener_proto_url_shortener_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UGResponse.ProtoReflect.Descriptor instead.
func (*UGResponse) Descriptor() ([]byte, []int) {
	return file_internal_url_shortener_proto_url_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *UGResponse) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

var File_internal_url_shortener_proto_url_shortener_proto protoreflect.FileDescriptor

var file_internal_url_shortener_proto_url_shortener_proto_rawDesc = []byte{
	0x0a, 0x30, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x75, 0x72, 0x6c, 0x5f, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75,
	0x72, 0x6c, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x22, 0x25, 0x0a, 0x09, 0x55, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x22, 0x28, 0x0a, 0x0a, 0x55,
	0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x27, 0x0a, 0x09, 0x55, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x26,
	0x0a, 0x0a, 0x55, 0x47, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c,
	0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x32, 0x9c, 0x01, 0x0a, 0x13, 0x55, 0x72, 0x6c, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43,
	0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x43, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x1b, 0x2e, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x47,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x47, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x3b, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_internal_url_shortener_proto_url_shortener_proto_rawDescOnce sync.Once
	file_internal_url_shortener_proto_url_shortener_proto_rawDescData = file_internal_url_shortener_proto_url_shortener_proto_rawDesc
)

func file_internal_url_shortener_proto_url_shortener_proto_rawDescGZIP() []byte {
	file_internal_url_shortener_proto_url_shortener_proto_rawDescOnce.Do(func() {
		file_internal_url_shortener_proto_url_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_url_shortener_proto_url_shortener_proto_rawDescData)
	})
	return file_internal_url_shortener_proto_url_shortener_proto_rawDescData
}

var file_internal_url_shortener_proto_url_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_url_shortener_proto_url_shortener_proto_goTypes = []interface{}{
	(*UCRequest)(nil),  // 0: shortenerService.UCRequest
	(*UCResponse)(nil), // 1: shortenerService.UCResponse
	(*UGRequest)(nil),  // 2: shortenerService.UGRequest
	(*UGResponse)(nil), // 3: shortenerService.UGResponse
}
var file_internal_url_shortener_proto_url_shortener_proto_depIdxs = []int32{
	0, // 0: shortenerService.UrlShortenerService.Create:input_type -> shortenerService.UCRequest
	2, // 1: shortenerService.UrlShortenerService.Get:input_type -> shortenerService.UGRequest
	1, // 2: shortenerService.UrlShortenerService.Create:output_type -> shortenerService.UCResponse
	3, // 3: shortenerService.UrlShortenerService.Get:output_type -> shortenerService.UGResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_url_shortener_proto_url_shortener_proto_init() }
func file_internal_url_shortener_proto_url_shortener_proto_init() {
	if File_internal_url_shortener_proto_url_shortener_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_url_shortener_proto_url_shortener_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_url_shortener_proto_url_shortener_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UCResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_url_shortener_proto_url_shortener_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_url_shortener_proto_url_shortener_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UGResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_url_shortener_proto_url_shortener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_url_shortener_proto_url_shortener_proto_goTypes,
		DependencyIndexes: file_internal_url_shortener_proto_url_shortener_proto_depIdxs,
		MessageInfos:      file_internal_url_shortener_proto_url_shortener_proto_msgTypes,
	}.Build()
	File_internal_url_shortener_proto_url_shortener_proto = out.File
	file_internal_url_shortener_proto_url_shortener_proto_rawDesc = nil
	file_internal_url_shortener_proto_url_shortener_proto_goTypes = nil
	file_internal_url_shortener_proto_url_shortener_proto_depIdxs = nil
}
