// Code generated by MockGen. DO NOT EDIT.
// Source: inmemory.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUSInmemory is a mock of USInmemory interface.
type MockUSInmemory struct {
	ctrl     *gomock.Controller
	recorder *MockUSInmemoryMockRecorder
}

// MockUSInmemoryMockRecorder is the mock recorder for MockUSInmemory.
type MockUSInmemoryMockRecorder struct {
	mock *MockUSInmemory
}

// NewMockUSInmemory creates a new mock instance.
func NewMockUSInmemory(ctrl *gomock.Controller) *MockUSInmemory {
	mock := &MockUSInmemory{ctrl: ctrl}
	mock.recorder = &MockUSInmemoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUSInmemory) EXPECT() *MockUSInmemoryMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockUSInmemory) Check() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check")
	ret0, _ := ret[0].(error)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockUSInmemoryMockRecorder) Check() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockUSInmemory)(nil).Check))
}

// Create mocks base method.
func (m *MockUSInmemory) Create(shortUrl, longUrl string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", shortUrl, longUrl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUSInmemoryMockRecorder) Create(shortUrl, longUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUSInmemory)(nil).Create), shortUrl, longUrl)
}

// GetLong mocks base method.
func (m *MockUSInmemory) GetLong(shortUrl string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLong", shortUrl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLong indicates an expected call of GetLong.
func (mr *MockUSInmemoryMockRecorder) GetLong(shortUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLong", reflect.TypeOf((*MockUSInmemory)(nil).GetLong), shortUrl)
}

// GetShort mocks base method.
func (m *MockUSInmemory) GetShort(longUrl string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShort", longUrl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShort indicates an expected call of GetShort.
func (mr *MockUSInmemoryMockRecorder) GetShort(longUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShort", reflect.TypeOf((*MockUSInmemory)(nil).GetShort), longUrl)
}
