// Code generated by MockGen. DO NOT EDIT.
// Source: pg_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/restlesswhy/grpc/url-shortener-microservice/internal/models"
)

// MockUrlShortenerRepository is a mock of UrlShortenerRepository interface.
type MockUrlShortenerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUrlShortenerRepositoryMockRecorder
}

// MockUrlShortenerRepositoryMockRecorder is the mock recorder for MockUrlShortenerRepository.
type MockUrlShortenerRepositoryMockRecorder struct {
	mock *MockUrlShortenerRepository
}

// NewMockUrlShortenerRepository creates a new mock instance.
func NewMockUrlShortenerRepository(ctrl *gomock.Controller) *MockUrlShortenerRepository {
	mock := &MockUrlShortenerRepository{ctrl: ctrl}
	mock.recorder = &MockUrlShortenerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlShortenerRepository) EXPECT() *MockUrlShortenerRepositoryMockRecorder {
	return m.recorder
}

// CreateRepo mocks base method.
func (m *MockUrlShortenerRepository) CreateRepo(ctx context.Context, longUrl, shortUrl string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRepo", ctx, longUrl, shortUrl)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRepo indicates an expected call of CreateRepo.
func (mr *MockUrlShortenerRepositoryMockRecorder) CreateRepo(ctx, longUrl, shortUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRepo", reflect.TypeOf((*MockUrlShortenerRepository)(nil).CreateRepo), ctx, longUrl, shortUrl)
}

// GetRepo mocks base method.
func (m *MockUrlShortenerRepository) GetRepo(ctx context.Context, longUrl, shortUrl string) (models.UrlsLS, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepo", ctx, longUrl, shortUrl)
	ret0, _ := ret[0].(models.UrlsLS)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetRepo indicates an expected call of GetRepo.
func (mr *MockUrlShortenerRepositoryMockRecorder) GetRepo(ctx, longUrl, shortUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepo", reflect.TypeOf((*MockUrlShortenerRepository)(nil).GetRepo), ctx, longUrl, shortUrl)
}
